### ISSUE TITLE
Wat voor game

### ISSUE THREAD

**Issue by Juaopteinde** [Juaopteinde/Project-Whip#3]

**Comment by appie857** [comment]
Desnoods kunnen we simpel beginnen met een  vampire survivors achtige game terwijl we de echte gameplay loop gaan bedenken.

**Comment by timmeej** [comment]
fps roguelike is wel goed idee er is nog niet super veel in fps genre bij roguelikes. Ik dacht ook misschien dat het dan interessant was om een soort extraction mechanic te implementeren? SULFUR is een game die dit ook een beetje heeft maar die is meer fantasy style/dungeon crawler.

**Comment by pinkodingle** [comment]
Ik heb een beginsel van idee van een wereld/gameplay loop.
Elk level of iets dergelijks is zo'n sprookje van de gebroeders Grimm, dus de fokt op versie van hoe we die sprookjes nu kennen. En als de level progression of wat dan ook linear is, dan worden ze steeds meer fokt op, maar voor random heb ik nog niet echt een idee.

**Comment by pinkodingle** [comment]
Miss is dit niet de beste setting voor het soort spel dat we in gedachte hebben
